linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
      - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_CURRENT_PAGE="gcc_shared"
      - <<: *osx
        osx_image: xcode11.2
        env: CONAN_APPLE_CLANG_VERSIONS=11.0 CONAN_CURRENT_PAGE="apple-clang_shared"

install:
   - chmod +x .travis/install.sh
   - ./.travis/install.sh

script:
   - chmod +x .travis/run.sh
   - ./.travis/run.sh
   - cmake . -DBUILD_TESTS=TRUE
   - cmake --build . --target runUnitTests
